// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oe4lBNFQ3hoCblJUYuB3_4rQO1A50JY',
    appId: '1:377160965461:web:ee777db3e36e5c970b63dc',
    messagingSenderId: '377160965461',
    projectId: 'fluttertest-9220c',
    authDomain: 'fluttertest-9220c.firebaseapp.com',
    storageBucket: 'fluttertest-9220c.appspot.com',
    measurementId: 'G-7J32R1YM1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ25-ZMTP_PgityxPxifUm5Lx1rF6C1bE',
    appId: '1:377160965461:android:989f4d9c9c3d32960b63dc',
    messagingSenderId: '377160965461',
    projectId: 'fluttertest-9220c',
    storageBucket: 'fluttertest-9220c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbPih_p7yejIXSG_SRfz2EExQLVot22k',
    appId: '1:377160965461:ios:109b829e4f56caac0b63dc',
    messagingSenderId: '377160965461',
    projectId: 'fluttertest-9220c',
    storageBucket: 'fluttertest-9220c.appspot.com',
    iosBundleId: 'com.start.insights.startinsights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbPih_p7yejIXSG_SRfz2EExQLVot22k',
    appId: '1:377160965461:ios:2dca21bf208b44c50b63dc',
    messagingSenderId: '377160965461',
    projectId: 'fluttertest-9220c',
    storageBucket: 'fluttertest-9220c.appspot.com',
    iosBundleId: 'com.start.insights.startinsights.RunnerTests',
  );
}
